=== nahiarasg/SEW/F1Desktop/xml/circuito.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.uniovi.es" xmlns="http://www.uniovi.es" elementFormDefault="qualified">

	<!-- atributos globales-->
	<xs:simpleType name="unidades">
		<xs:restriction base="xs:string">
			<xs:enumeration value="cm" />
			<xs:enumeration value="m" />
			<xs:enumeration value="km" />
		</xs:restriction>
	</xs:simpleType>

	<!-- Definición de un decimal positivo -->
	<xs:simpleType name="decimalPositivo">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
	
	
	<!-- elementos y atributos-->
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitudCircuito" />
				<xs:element ref="anchura" />
				<xs:element ref="fecha" />
				<xs:element ref="hora" />
				<xs:element ref="vueltas" />
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
				<xs:element ref="referencias" />
				<xs:element ref="fototeca" />
				<xs:element ref="galeria" minOccurs="0" />
				<xs:element ref="coordenadas" />
				<xs:element ref="trazosCircuito" />
			</xs:sequence>
			<xs:attribute name="nombre" type="xs:string" use="required" />
		</xs:complexType>
	
		<!-- longitud -->
		</xs:element>
		<xs:element name="nombre" type="xs:string" />
		<xs:element name="longitudCircuito">
			<xs:complexType>
				<xs:simpleContent>
					<xs:extension base="decimalPositivo">
						<xs:attribute name="unidades" type="unidades" use="required" />
					</xs:extension>
				</xs:simpleContent>
			</xs:complexType>
		</xs:element>

		<!-- anchura -->
		<xs:element name="anchura">
			<xs:complexType>
				<xs:simpleContent>
					<xs:extension base="decimalPositivo">
						<xs:attribute name="unidades" type="unidades" use="required" />
					</xs:extension>
				</xs:simpleContent>
			</xs:complexType>
		</xs:element>

		<!-- fecha -->
		<xs:element name="fecha" type="xs:date"/>


		<!-- hora -->
		<xs:element name="hora" type="xs:string" />

		<!-- vueltas -->
		<xs:element name="vueltas">
			<xs:simpleType>
				<xs:restriction base="xs:int">
					<xs:minInclusive value="0"/> <!-- Permite solo valores 0 o positivos -->
				</xs:restriction>
			</xs:simpleType>
		</xs:element>

		<!-- localidad -->
		<xs:element name="localidad" type="xs:string" />

		<!-- país -->
		<xs:element name="pais" type="xs:string" />

		<!-- referencias -->
		<xs:element name="referencias">
			<xs:complexType>
				<xs:sequence>
					<xs:element minOccurs="1" maxOccurs="unbounded" ref="link" />
				</xs:sequence>
			</xs:complexType>
		</xs:element>

		<xs:element name="link">
			<xs:complexType>
				<xs:simpleContent>
					<xs:extension base="xs:anyURI">
						<xs:attribute name="linkName" type="xs:string" use="required" />
					</xs:extension>
				</xs:simpleContent>
			</xs:complexType>
		</xs:element>

		<!-- fototeca -->
		<xs:element name="fototeca">
			<xs:complexType>
				<xs:sequence>
					<xs:element minOccurs="1" maxOccurs="unbounded" ref="imagen" />
				</xs:sequence>
			</xs:complexType>
		</xs:element>

		<xs:element name="imagen">
			<xs:complexType>
				<xs:simpleContent>
					<xs:extension base="xs:anyURI">
						 <xs:attribute name="formato" type="xs:string" use="optional" />
						<xs:attribute name="descripcion" type="xs:string" use="optional" />
					</xs:extension>
				</xs:simpleContent>
			</xs:complexType>
		</xs:element>

		<!-- galeria -->
		<xs:element name="galeria">
			<xs:complexType>
				<xs:sequence>
					<xs:element minOccurs="0" maxOccurs="unbounded" ref="video" />
				</xs:sequence>
			</xs:complexType>
		</xs:element>
	
		<xs:element name="video">
			<xs:complexType>
				<xs:simpleContent>
					<xs:extension base="xs:anyURI">
						<xs:attribute name="formato" type="xs:string" use="optional" />
						<xs:attribute name="descripcion" type="xs:string" use="optional" />
					</xs:extension>
				</xs:simpleContent>
			</xs:complexType>
		</xs:element>

		<!-- coordenadas -->
		<xs:element name="coordenadas">
			<xs:complexType>
				<xs:sequence>
					<xs:element ref="longitud" />
					<xs:element ref="latitud" />
					<xs:element ref="altitud" />
				</xs:sequence>
			</xs:complexType>
		</xs:element>

		<xs:element name="longitud" type="xs:decimal" />
		<xs:element name="latitud" type="xs:decimal" />
		<xs:element name="altitud">
    		<xs:complexType>
        		<xs:simpleContent>
            		<xs:extension base="xs:decimal">
                		<xs:attribute name="unidades" type="xs:string" use="required"/>
            		</xs:extension>
        		</xs:simpleContent>
    		</xs:complexType>
		</xs:element>

		<!-- trazos circuito -->
		<xs:element name="trazosCircuito">
			<xs:complexType>
				<xs:sequence>
					<xs:element minOccurs="1" maxOccurs="unbounded" ref="sector" />
				</xs:sequence>
			</xs:complexType>
		</xs:element>

		<xs:element name="sector">
			<xs:complexType>
				<xs:sequence>
					<xs:element ref="distanciaTramo" />
					<xs:element ref="coordenadas" />
					<xs:element ref="numSector" />
				</xs:sequence>

				<xs:attribute name="id" type="xs:integer" use="required" />
			</xs:complexType>
		</xs:element>

		<xs:element name="distanciaTramo">
			<xs:complexType>
				<xs:simpleContent>
					<xs:extension base="decimalPositivo">
						<xs:attribute name="unidades" type="unidades" use="required" />
					</xs:extension>
				</xs:simpleContent>
			</xs:complexType>
		</xs:element>

		<xs:element name="numSector" type="xs:integer" />
	
</xs:schema>

=== nahiarasg/SEW/F1Desktop/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<uniovi:circuito xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xmlns:uniovi="http://www.uniovi.es"
                 xsi:schemaLocation="http://www.uniovi.es circuito.xsd"
                 nombre="SPA-FRANCORCHAMPS">


    <uniovi:nombre>SPA-FRANCORCHAMPS</uniovi:nombre>
    <uniovi:longitudCircuito unidades="km">7.004</uniovi:longitudCircuito>
    <uniovi:anchura unidades="m">8</uniovi:anchura>
    <uniovi:fecha>2024-06-28</uniovi:fecha>
    <uniovi:hora>15:00</uniovi:hora>
    <uniovi:vueltas>44</uniovi:vueltas>
    <uniovi:localidad>Stavelot</uniovi:localidad>
    <uniovi:pais>BÃ©lgica</uniovi:pais>

    <uniovi:referencias>
        <uniovi:link linkName="Circuito Spa-Francorchamps">
            https://www.circuitosdecarreras.com/belgica/circuito-spa-francorchamps/</uniovi:link>
        <uniovi:link linkName="Dazn - Circuito Spa-Francorchamps">
            https://www.dazn.com/es-ES/news/motor/circuito-spa-francorchamps-donde-esta-como-es-caracteristicas-como-llegar-fotos-escenario-gp-belgica-mundial-f1/iruciknj8sid1e37zg80cgdec</uniovi:link>
        <uniovi:link linkName="Wikipedia - Circuito Spa-Francorchamps">
            https://es.wikipedia.org/wiki/Circuito_de_Spa-Francorchamps</uniovi:link>
    </uniovi:referencias>

    <uniovi:fototeca>
        <uniovi:imagen formato="jpg" descripcion="Pista del circuito">multimedia/images/pistaCircuito.jpg</uniovi:imagen>
        <uniovi:imagen formato="jpg" descripcion="Salida del circuito">multimedia/images/salidaCircuito.jpg</uniovi:imagen>
        <uniovi:imagen formato="jpg" descripcion="Carrera en el circuito">multimedia/images/carreraCircuito.jpg</uniovi:imagen>
    </uniovi:fototeca>

    <uniovi:galeria>
        <uniovi:video formato="mp4" descripcion="Video del circuito">multimedia/videos/circuito.mp4</uniovi:video>
    </uniovi:galeria>

    <uniovi:coordenadas>
        <uniovi:longitud>5.96</uniovi:longitud>
        <uniovi:latitud>50.44</uniovi:latitud>
        <uniovi:altitud unidades="m">410.71</uniovi:altitud>
    </uniovi:coordenadas>

    <uniovi:trazosCircuito>
        <uniovi:sector id="1">
            <uniovi:distanciaTramo unidades = "m">294.23</uniovi:distanciaTramo>
            <uniovi:coordenadas>
                <uniovi:longitud>5.967075555216246</uniovi:longitud>
                <uniovi:latitud>50.44195911018055</uniovi:latitud>
                <uniovi:altitud unidades="m">410.71</uniovi:altitud>
            </uniovi:coordenadas>
            <uniovi:numSector>1</uniovi:numSector>
        </uniovi:sector>
    
        <uniovi:sector id="2">
            <uniovi:distanciaTramo unidades="m">18.97</uniovi:distanciaTramo>
            <uniovi:coordenadas>
                <uniovi:longitud>5.964968657789322</uniovi:longitud>
                <uniovi:latitud>50.4442804712973</uniovi:latitud>
                <uniovi:altitud unidades="m">409.23</uniovi:altitud>
            </uniovi:coordenadas>
            <uniovi:numSector>1</uniovi:numSector>
        </uniovi:sector>
    
        <uniovi:sector id="3">
            <uniovi:distanciaTramo unidades="m">17.02</uniovi:distanciaTramo>
            <uniovi:coordenadas>
                <uniovi:longitud>5.963342055038769</uniovi:longitud>
                <uniovi:latitud>50.44607575122644</uniovi:latitud>
                <uniovi:altitud unidades="m">409.02</uniovi:altitud>
            </uniovi:coordenadas>
            <uniovi:numSector>1</uniovi:numSector>
        </uniovi:sector>
    
        <uniovi:sector id="4">
            <uniovi:distanciaTramo unidades="m">13.56</uniovi:distanciaTramo>
            <uniovi:coordenadas>
                <uniovi:longitud>5.963475630413411</uniovi:longitud>
                <uniovi:latitud>50.44624469387168</uniovi:latitud>
                <uniovi:altitud unidades="m">407.99</uniovi:altitud>
            </uniovi:coordenadas>
            <uniovi:numSector>1</uniovi:numSector>
        </uniovi:sector>
    
        <uniovi:sector id="5">
            <uniovi:distanciaTramo unidades="m">12.98</uniovi:distanciaTramo>
            <uniovi:coordenadas>
                <uniovi:longitud>5.965744182488082</uniovi:longitud>
                <uniovi:latitud>50.4455854614964</uniovi:latitud>
                <uniovi:altitud unidades="m">407.15</uniovi:altitud>
            </uniovi:coordenadas>
            <uniovi:numSector>1</uniovi:numSector>
        </uniovi:sector>
    
        <uniovi:sector id="6">
            <uniovi:distanciaTramo unidades="m">33.94</uniovi:distanciaTramo>
            <uniovi:coordenadas>
                <uniovi:longitud>5.966860028543377</uniovi:longitud>
                <uniovi:latitud>50.44510169183539</uniovi:latitud>
                <uniovi:altitud unidades="m">407.15</uniovi:altitud>
            </uniovi:coordenadas>
            <uniovi:numSector>1</uniovi:numSector>
        </uniovi:sector>
    
        <uniovi:sector id="7">
            <uniovi:distanciaTramo unidades="m">12.7</uniovi:distanciaTramo>
            <uniovi:coordenadas>
                <uniovi:longitud>5.967566741884964</uniovi:longitud>
                <uniovi:latitud>50.44468402042162</uniovi:latitud>
                <uniovi:altitud unidades="m">406.11</uniovi:altitud>
            </uniovi:coordenadas>
            <uniovi:numSector>1</uniovi:numSector>
        </uniovi:sector>
    
        <uniovi:sector id="8">
            <uniovi:distanciaTramo unidades="m">12.54</uniovi:distanciaTramo>
            <uniovi:coordenadas>
                <uniovi:longitud>5.970402777494918</uniovi:longitud>
                <uniovi:latitud>50.44254778423586</uniovi:latitud>
                <uniovi:altitud unidades="m">406.07</uniovi:altitud>
            </uniovi:coordenadas>
            <uniovi:numSector>1</uniovi:numSector>
        </uniovi:sector>
    
        <uniovi:sector id="9">
            <uniovi:distanciaTramo unidades="m">224.58</uniovi:distanciaTramo>
            <uniovi:coordenadas>
                <uniovi:longitud>5.971468915433151</uniovi:longitud>
                <uniovi:latitud>50.44210024337618</uniovi:latitud>
                <uniovi:altitud unidades="m">416.47</uniovi:altitud>
            </uniovi:coordenadas>
            <uniovi:numSector>1</uniovi:numSector>
        </uniovi:sector>
    
        <uniovi:sector id="10">
            <uniovi:distanciaTramo unidades="m">56.26</uniovi:distanciaTramo>
            <uniovi:coordenadas>
                <uniovi:longitud>5.971902575596491</uniovi:longitud>
                <uniovi:latitud>50.44153383973529</uniovi:latitud>
                <uniovi:altitud unidades="m">416.47</uniovi:altitud>
            </uniovi:coordenadas>
            <uniovi:numSector>1</uniovi:numSector>
        </uniovi:sector>
    
        <uniovi:sector id="11">
            <uniovi:distanciaTramo unidades="m">229.3</uniovi:distanciaTramo>
            <uniovi:coordenadas>
                <uniovi:longitud>5.972039366224395</uniovi:longitud>
                <uniovi:latitud>50.44096511523191</uniovi:latitud>
                <uniovi:altitud unidades="m">414.16</uniovi:altitud>
            </uniovi:coordenadas>
            <uniovi:numSector>1</uniovi:numSector>
        </uniovi:sector>
    
        <uniovi:sector id="12">
            <uniovi:distanciaTramo unidades="m">57.49</uniovi:distanciaTramo>
            <uniovi:coordenadas>
                <uniovi:longitud>5.97219412547477</uniovi:longitud>
                <uniovi:latitud>50.44067005150603</uniovi:latitud>
                <uniovi:altitud unidades="m">415.55</uniovi:altitud>
            </uniovi:coordenadas>
            <uniovi:numSector>1</uniovi:numSector>
        </uniovi:sector>
    
        <uniovi:sector id="13">
            <uniovi:distanciaTramo unidades="m">202.84</uniovi:distanciaTramo>
            <uniovi:coordenadas>
                <uniovi:longitud>5.974259209154768</uniovi:longitud>
                <uniovi:latitud>50.43867515888307</uniovi:latitud>
                <uniovi:altitud unidades="m">397.05</uniovi:altitud>
            </uniovi:coordenadas>
            <uniovi:numSector>1</uniovi:numSector>
        </uniovi:sector>
    
        <uniovi:sector id="14">
            <uniovi:distanciaTramo unidades="m">78.88</uniovi:distanciaTramo>
            <uniovi:coordenadas>
                <uniovi:longitud>5.974554271861576</uniovi:longitud>
                <uniovi:latitud>50.43826866282627</uniovi:latitud>
                <uniovi:altitud unidades="m">383.41</uniovi:altitud>
            </uniovi:coordenadas>
            <uniovi:numSector>1</uniovi:numSector>
        </uniovi:sector>
    
        <uniovi:sector id="15">
            <uniovi:distanciaTramo unidades="m">83.16</uniovi:distanciaTramo>
            <uniovi:coordenadas>
                <uniovi:longitud>5.977570554565562</uniovi:longitud>
                <uniovi:latitud>50.43155857802816</uniovi:latitud>
                <uniovi:altitud unidades="m">376.38</uniovi:altitud>
            </uniovi:coordenadas>
            <uniovi:numSector>1</uniovi:numSector>
        </uniovi:sector>
    
        <uniovi:sector id="16">
            <uniovi:distanciaTramo unidades="m">169.98</uniovi:distanciaTramo>
            <uniovi:coordenadas>
                <uniovi:longitud>5.977487163801907</uniovi:longitud>
                <uniovi:latitud>50.43130200200452</uniovi:latitud>
                <uniovi:altitud unidades="m">375.74</uniovi:altitud>
            </uniovi:coordenadas>
            <uniovi:numSector>1</uniovi:numSector>
        </uniovi:sector>
    
        <uniovi:sector id="17">
            <uniovi:distanciaTramo unidades="m">71.04</uniovi:distanciaTramo>
            <uniovi:coordenadas>
                <uniovi:longitud>5.977258823195603</uniovi:longitud>
