=== nahiarasg/SEW/xml/circuito.dtd
<!ELEMENT circuito (nombre, longitudCircuito, anchura, fecha, hora, vueltas,
                    localidad, pais, referencias, fototeca, galeria,
                    coordenadas, trazosCircuito)>

<!ATTLIST circuito nombre CDATA #REQUIRED >

<!ELEMENT nombre (#PCDATA)>

<!ELEMENT longitudCircuito (#PCDATA) >
<!ATTLIST longitudCircuito unidades CDATA #REQUIRED >

<!ELEMENT anchura (#PCDATA) >
<!ATTLIST anchura unidades CDATA #REQUIRED >

<!ELEMENT fecha (dia, mes, año)>
<!ELEMENT dia (#PCDATA) >
<!ELEMENT mes (#PCDATA) >
<!ELEMENT año (#PCDATA) >

<!ELEMENT hora (#PCDATA) >

<!ELEMENT vueltas (#PCDATA) >

<!ELEMENT localidad (#PCDATA) >

<!ELEMENT pais (#PCDATA)>

<!ELEMENT referencias (link+)>
<!ELEMENT link (#PCDATA)>
<!ATTLIST link linkName CDATA #REQUIRED>

<!ELEMENT fototeca (imagen+)>
<!ELEMENT imagen (#PCDATA)>

<!ELEMENT galeria (video*)>
<!ELEMENT video (#PCDATA)>

<!ELEMENT coordenadas (longitud, latitud, altitud)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>

<!ELEMENT trazosCircuito (sector+)>
<!ELEMENT sector (distanciaTramo, coordenadas, numSector)>
<!ATTLIST sector id CDATA #REQUIRED>
<!ELEMENT distanciaTramo (#PCDATA)>
<!ATTLIST distanciaTramo unidades CDATA #REQUIRED>
<!ELEMENT numSector (#PCDATA)>

=== nahiarasg/SEW/F1Desktop/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">

<circuito nombre = "SPA-FRANCORCHAMPS">

<nombre>SPA-FRANCORCHAMPS</nombre>
<longitudCircuito unidades = "km">7.004</longitudCircuito>
<anchura unidades="m">8</anchura>
<fecha>
    <dia>28</dia>
    <mes>julio</mes>
    <año>2024</año>
</fecha>
<hora>15:00</hora>
<vueltas>44</vueltas>
<localidad>Stavelot</localidad>
<pais>Bélgica</pais>

<referencias>
    <link linkName="Circuito Spa-Francorchamps">https://www.circuitosdecarreras.com/belgica/circuito-spa-francorchamps/</link>
    <link linkName="Dazn - Circuito Spa-Francorchamps">https://www.dazn.com/es-ES/news/motor/circuito-spa-francorchamps-donde-esta-como-es-caracteristicas-como-llegar-fotos-escenario-gp-belgica-mundial-f1/iruciknj8sid1e37zg80cgdec</link>
    <link linkName="Wikipedia - Circuito Spa-Francorchamps">https://es.wikipedia.org/wiki/Circuito_de_Spa-Francorchamps</link>
</referencias>

<fototeca>
    <imagen>"/multimedia/images/pistaCircuito.jpg"</imagen>
    <imagen>"/multimedia/images/salidaCircuito.jpg"</imagen>
    <imagen>"/multimedia/images/carreraCircuito.jpg"</imagen>
</fototeca>

<galeria>
    <video>"circuito.mp4"</video>
</galeria>

<coordenadas>
    <longitud>5.96</longitud>
    <latitud>50.44</latitud>
    <altitud>410.71 m</altitud>
</coordenadas>

<trazosCircuito>
    
    <sector id="1">
        <distanciaTramo unidades = "m">294.23</distanciaTramo>
        <coordenadas>
            <longitud>5.967075555216246</longitud>
            <latitud>50.44195911018055</latitud>
            <altitud>410.71</altitud>
        </coordenadas>
        <numSector>1</numSector>
    </sector>

    <sector id="2">
        <distanciaTramo unidades="m">18.97</distanciaTramo>
        <coordenadas>
            <longitud>5.964968657789322</longitud>
            <latitud>50.4442804712973</latitud>
            <altitud>409.23</altitud>
        </coordenadas>
        <numSector>1</numSector>
    </sector>

    <sector id="3">
        <distanciaTramo unidades="m">17.02</distanciaTramo>
        <coordenadas>
            <longitud>5.963342055038769</longitud>
            <latitud>50.44607575122644</latitud>
            <altitud>409.02</altitud>
        </coordenadas>
        <numSector>1</numSector>
    </sector>

    <sector id="4">
        <distanciaTramo unidades="m">13.56</distanciaTramo>
        <coordenadas>
            <longitud>5.963475630413411</longitud>
            <latitud>50.44624469387168</latitud>
            <altitud>407.99</altitud>
        </coordenadas>
        <numSector>1</numSector>
    </sector>

    <sector id="5">
        <distanciaTramo unidades="m">12.98</distanciaTramo>
        <coordenadas>
            <longitud>5.965744182488082</longitud>
            <latitud>50.4455854614964</latitud>
            <altitud>407.15</altitud>
        </coordenadas>
        <numSector>1</numSector>
    </sector>

    <sector id="6">
        <distanciaTramo unidades="m">33.94</distanciaTramo>
        <coordenadas>
            <longitud>5.966860028543377</longitud>
            <latitud>50.44510169183539</latitud>
            <altitud>407.15</altitud>
        </coordenadas>
        <numSector>1</numSector>
    </sector>

    <sector id="7">
        <distanciaTramo unidades="m">12.7</distanciaTramo>
        <coordenadas>
            <longitud>5.967566741884964</longitud>
            <latitud>50.44468402042162</latitud>
            <altitud>406.11</altitud>
        </coordenadas>
        <numSector>1</numSector>
    </sector>

    <sector id="8">
        <distanciaTramo unidades="m">12.54</distanciaTramo>
        <coordenadas>
            <longitud>5.970402777494918</longitud>
            <latitud>50.44254778423586</latitud>
            <altitud>406.07</altitud>
        </coordenadas>
        <numSector>1</numSector>
    </sector>

    <sector id="9">
        <distanciaTramo unidades="m">224.58</distanciaTramo>
        <coordenadas>
            <longitud>5.971468915433151</longitud>
            <latitud>50.44210024337618</latitud>
            <altitud>416.47</altitud>
        </coordenadas>
        <numSector>1</numSector>
    </sector>

    <sector id="10">
        <distanciaTramo unidades="m">56.26</distanciaTramo>
        <coordenadas>
            <longitud>5.971902575596491</longitud>
            <latitud>50.44153383973529</latitud>
            <altitud>416.47</altitud>
        </coordenadas>
        <numSector>1</numSector>
    </sector>

    <sector id="11">
        <distanciaTramo unidades="m">229.3</distanciaTramo>
        <coordenadas>
            <longitud>5.972039366224395</longitud>
            <latitud>50.44096511523191</latitud>
            <altitud>414.16</altitud>
        </coordenadas>
        <numSector>1</numSector>
    </sector>

    <sector id="12">
        <distanciaTramo unidades="m">57.49</distanciaTramo>
        <coordenadas>
            <longitud>5.97219412547477</longitud>
            <latitud>50.44067005150603</latitud>
            <altitud>415.55</altitud>
        </coordenadas>
        <numSector>1</numSector>
    </sector>

    <sector id="13">
        <distanciaTramo unidades="m">202.84</distanciaTramo>
        <coordenadas>
            <longitud>5.974259209154768</longitud>
            <latitud>50.43867515888307</latitud>
            <altitud>397.05</altitud>
        </coordenadas>
        <numSector>1</numSector>
    </sector>

    <sector id="14">
        <distanciaTramo unidades="m">78.88</distanciaTramo>
        <coordenadas>
            <longitud>5.974554271861576</longitud>
            <latitud>50.43826866282627</latitud>
            <altitud>383.41</altitud>
        </coordenadas>
        <numSector>1</numSector>
    </sector>

    <sector id="15">
        <distanciaTramo unidades="m">83.16</distanciaTramo>
        <coordenadas>
            <longitud>5.977570554565562</longitud>
            <latitud>50.43155857802816</latitud>
            <altitud>376.38</altitud>
        </coordenadas>
        <numSector>1</numSector>
    </sector>

    <sector id="16">
        <distanciaTramo unidades="m">169.98</distanciaTramo>
        <coordenadas>
            <longitud>5.977487163801907</longitud>
            <latitud>50.43130200200452</latitud>
            <altitud>375.74</altitud>
        </coordenadas>
        <numSector>1</numSector>
    </sector>

    <sector id="17">
        <distanciaTramo unidades="m">71.04</distanciaTramo>
        <coordenadas>
            <longitud>5.977258823195603</longitud>
            <latitud>50.43114093370707</latitud>
            <altitud>375.74</altitud>
        </coordenadas>
        <numSector>1</numSector>
    </sector>

    <sector id="18">
        <distanciaTramo unidades="m">136.13</distanciaTramo>
        <coordenadas>
            <longitud>5.976798224852377</longitud>
            <latitud>50.43094919522218</latitud>
            <altitud>367.72</altitud>
        </coordenadas>
        <numSector>1</numSector>
    </sector>

    <sector id="19">
        <distanciaTramo unidades="m">68.37</distanciaTramo>
        <coordenadas>
            <longitud>5.97666419522654</longitud>
            <latitud>50.43066500941418</latitud>
            <altitud>367.72</altitud>
        </coordenadas>
        <numSector>1</numSector>
    </sector>

    <sector id="20">
        <distanciaTramo unidades="m">71.03</distanciaTramo>
        <coordenadas>
            <longitud>5.977024516152696</longitud>
            <latitud>50.42975535669468</latitud>
            <altitud>364.38</altitud>
        </coordenadas>
        <numSector>1</numSector>
    </sector>

    <sector id="22">
        <distanciaTramo unidades="m">57.2</distanciaTramo>
        <coordenadas>
            <longitud>5.976969797768533</longitud>
            <latitud></latitud>
            <altitud>364.38</altitud>
        </coordenadas>
        <numSector>2</numSector>
    </sector>

    <sector id="23">
        <distanciaTramo unidades="m">68.37</distanciaTramo>
        <coordenadas>
            <longitud>5.976793258001127</longitud>
            <latitud>50.42929859905469</latitud>
            <altitud>365.55</altitud>
        </coordenadas>
        <numSector>2</numSector>
    </sector>

    <sector id="24">
        <distanciaTramo unidades="m">31.44</distanciaTramo>
        <coordenadas>
            <longitud>5.973160779008269</longitud>
            <latitud>50.42769511235448</latitud>
            <altitud>368.43</altitud>
        </coordenadas>
        <numSector>2</numSector>
    </sector>

    <sector id="25">
        <distanciaTramo unidades="m">195.58</distanciaTramo>
        <coordenadas>
            <longitud>5.972589668686035</longitud>
            <latitud>50.42769558822935</latitud>
            <altitud>371.49</altitud>
        </coordenadas>
        <numSector>2</numSector>
    </sector>

    <sector id="26">
        <distanciaTramo unidades="m">44.11</distanciaTramo>
        <coordenadas>
            <longitud>5.972254898166249</longitud>
            <latitud>50.42790894494969</latitud>
            <altitud>371.50</altitud>
        </coordenadas>
        <numSector>2</numSector>
    </sector>

    <sector id="27">
        <distanciaTramo unidades="m">35.25</distanciaTramo>
        <coordenadas>
            <longitud>5.972192804758814</longitud>
            <latitud>50.4282077698665</latitud>
            <altitud>375.05</altitud>
        </coordenadas>
        <numSector>2</numSector>
    </sector>

    <sector id="28">
        <distanciaTramo unidades="m">91.75</distanciaTramo>
        <coordenadas>
            <longitud>5.972411626196143</longitud>
            <latitud>50.42845677091712</latitud>
            <altitud>375.88</altitud>
